Allowed for multiple apk paths of the same package

diff --git a/user_backup b/user_backup
--- a/user_backup
+++ b/user_backup
@@ -39,27 +39,31 @@ do
   fi
   
   # Find the package path
-  PKG_PATH=$(adb shell pm path "$PKG_NAME" | cut -d ':' -f2)
-  if [ -z $PKG_PATH ]; then
-    echo "Could not find the path of: $PKG_NAME"
-    adb disconnect > /dev/null
-    exit 1
-  else
-    echo "The package path is: $PKG_PATH"
-  fi
-  
-  # Backup the apk
-  printf "Backing up $PKG_PATH to $(pwd)/backups/$PKG_NAME.apk\n\n"
-  sleep 3
-  adb pull "$PKG_PATH" backups/"$PKG_NAME".apk
-  if [ $? -eq 0 ]; then
-    echo "Success!"
+  while IFS= read -r -u10 VERSION
+  do
+    if [ -z $VERSION ]; then
+      echo "Could not find the path of: $PKG_NAME"
+      adb disconnect > /dev/null
+      exit 1
+    else
+      echo "The package path is: $VERSION"
+    fi
+
+    PKG_VER_NAME=$(basename "$VERSION")
+    
+    # Backup the apk
+    printf "Backing up $VERSION to $(pwd)/backups/$PKG_NAME-$PKG_VER_NAME\n\n"
     sleep 3
-  else
-    echo "Backup failed..."
-    adb disconnect > /dev/null
-    exit 1
-  fi
+    adb pull "$PKG_PATH" backups/"$PKG_NAME-$PKG_VER_NAME"
+    if [ $? -eq 0 ]; then
+      echo "Success!"
+      sleep 3
+    else
+      echo "Backup failed..."
+      adb disconnect > /dev/null
+      exit 1
+    fi
+  done 10< <(adb shell pm path "$PKG_NAME" | cut -d ':' -f2)
   
   ## APP DATA BACKUP
   printf "\n### APP DATA BACKUP ###\n"
